tags:
 - name: Product
   sumary: Everything about products
paths: 
 /api/products:
  get:
   tags: 
     - Product
   summary: Get all products.Obtiene todos los productos 
   responses:	
    "200":
      description: Los productos fueron obtenidos satisfactoriamente de la base de datos
      content:
       application/json:
        schema:
         type: array
         items:
          $ref: '#components/schemas/Product'
    "500": 
      description: Error del servidor
  post:
   tags:
    - Product
   summary: Add a new product to the database
   responses:	
    "200":
     description: Create a new product in the database
    "500": 
      description: Error del servidor
 /api/products/:id:
  put:
   tags:
    - Product
   summary: Update a product in the database
   parameters:
    - name: id
      in: path
      required: true
   responses:	
    "200":
     description: Uodate a product in the database for id
    "500": 
     description: Error del servidor
  delete:
   tags:
    - Product
   summary: Delete a product in the database by its id
   responses:
    "200":
     description: Delete a product in the database
    "500": 
     description: Error al eliminar product

